name: Sync

on:
  push:
  schedule:
  - cron: 0 0 * * *
  workflow_dispatch:

env:
  AUTH_TOKEN: ${{ secrets.SYNC_TOKEN }}

jobs:
  job:
    name: Sync Labels
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Sync Labels
      uses: ShineyDev/sync-labels-action@main
      with:
        token: ${{ env.AUTH_TOKEN }}
        verbosity: 4
